# Steps taken from https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/step-by-step-installation/wazuh-cluster/wazuh_multi_node_cluster.html#wazuh-multi-node-cluster
ARG IMAGE_NAME=debian
ARG IMAGE_TAG=stretch-slim
FROM ${IMAGE_NAME}:${IMAGE_TAG}
RUN apt update
RUN apt -y install curl apt-transport-https lsb-release gnupg procps net-tools wget xmlstarlet
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
RUN echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
RUN apt update
RUN apt -y install wazuh-agent python3-pip
RUN python3 -m pip install boto3
RUN python3 -m pip install google-cloud-pubsub
RUN python3 -m pip install docker
RUN update-rc.d wazuh-agent defaults 95 10
ADD entrypoint-agent.sh /docker-entrypoint.sh
RUN chmod o+x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 514/tcp 514/udp 5514/tcp 5514/udp
